// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOqG4dKmPw5FRcqlBu3H1rGt0k_AOXCUo',
    appId: '1:472322449251:web:2fe0aac5d542698035bd56',
    messagingSenderId: '472322449251',
    projectId: 'expense-tracker-d023c',
    authDomain: 'expense-tracker-d023c.firebaseapp.com',
    storageBucket: 'expense-tracker-d023c.appspot.com',
    measurementId: 'G-TP26HD6LWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlT22oIsFaDhtfrVzeB4ZrVcMbvoW8fX8',
    appId: '1:472322449251:android:ff1d8b1fe66e025735bd56',
    messagingSenderId: '472322449251',
    projectId: 'expense-tracker-d023c',
    storageBucket: 'expense-tracker-d023c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9NrLYeCUEJgDDqM8DYSrlzBf1wLnd6Ww',
    appId: '1:472322449251:ios:d1191425f9490b6a35bd56',
    messagingSenderId: '472322449251',
    projectId: 'expense-tracker-d023c',
    storageBucket: 'expense-tracker-d023c.appspot.com',
    iosBundleId: 'com.example.expancetracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9NrLYeCUEJgDDqM8DYSrlzBf1wLnd6Ww',
    appId: '1:472322449251:ios:d1191425f9490b6a35bd56',
    messagingSenderId: '472322449251',
    projectId: 'expense-tracker-d023c',
    storageBucket: 'expense-tracker-d023c.appspot.com',
    iosBundleId: 'com.example.expancetracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOqG4dKmPw5FRcqlBu3H1rGt0k_AOXCUo',
    appId: '1:472322449251:web:1a10da11267ebae035bd56',
    messagingSenderId: '472322449251',
    projectId: 'expense-tracker-d023c',
    authDomain: 'expense-tracker-d023c.firebaseapp.com',
    storageBucket: 'expense-tracker-d023c.appspot.com',
    measurementId: 'G-2GRYF2NWBE',
  );
}
